#if !canImport(ObjectiveC)
import XCTest

extension xXxprojectxXxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__xXxprojectxXxTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(xXxprojectxXxTests.__allTests__xXxprojectxXxTests),
    ]
}
#endif
